exporter.baseDirectory = /app/output/
exporter.fhir.export = true
exporter.fhir_stu3.export = false
exporter.fhir_dstu2.export = false
exporter.hospital.fhir.export = true
exporter.practitioner.fhir.export = true
exporter.pretty_print = true
generate.providers.primarycare.default_file = providers/primary_care_facilities.csv
generate.providers.selection_behavior = random
generate.providers.maximum_search_distance = 1000